project_id = "lxxfhayifyiioglfbsyj"

[functions.generate-password-hash]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generate-manifest]
verify_jwt = false

[functions.staff-list-customers]
verify_jwt = false

[functions.staff-list-users]
verify_jwt = false

[functions.staff-list-orders]
verify_jwt = false