project_id = "lxxfhayifyiioglfbsyj"

[functions.generate-password-hash]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generate-manifest]
verify_jwt = false

[functions.staff-list-customers]
verify_jwt = false

[functions.customer-create-mp-preference]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.upload-pwa-icon]
verify_jwt = false

[functions.mapbox-geocode]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.process-auto-runas]
verify_jwt = false

[functions.mercadopago-diagnostics]
verify_jwt = false

[functions.send-staff-push]
verify_jwt = false

[functions.admin-manage-customer-auth]
verify_jwt = false

[functions.notify-wordpress-store-status]
verify_jwt = false

[functions.schedule-checker]
verify_jwt = false

[functions.lia-query]
verify_jwt = false





